services:
  spark_ingestor:
    build:
      context: ./streaming/spark_processor
      dockerfile: ./Dockerfile
    volumes:
      - ./feature_repo/offline_data:/app/offline_data
    container_name: spark_ingestor
    depends_on:
      broker-1:
        condition: service_healthy
    restart: unless-stopped

  kafka_producer:
    build:
      context: ./streaming/kafka_producer
      dockerfile: ./Dockerfile
    volumes:
      - ./feature_repo/offline_data:/app/offline_data
    container_name: kafka_producer
    depends_on:
      broker-1:
        condition: service_healthy
      spark_ingestor:
        condition: service_started
    environment:
      - KAFKA_BROKER=broker:9092
    restart: unless-stopped

  registry:
    container_name: registry
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=feast
    ports:
      - "55001:5432"
    volumes:
      - ./feast-postgres-registry:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    restart: unless-stopped

    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
      -c listen_addresses='*'
      -c max_connections=200

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

  broker-1:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker-1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "broker-1:9092", "--list" ]
      interval: 10s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  broker-2:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker-2
    ports:
      - "9093:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-2:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "broker-2:9092", "--list" ]
      interval: 10s
      retries: 5
      start_period: 20s
    restart: unless-stopped